name: qrcode_modal_example
description: An example app for QRCode modal

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  algorand_dart: ^1.0.1
  flutter:
    sdk: flutter
  walletconnect_dart: ^0.0.6
  walletconnect_qrcode_modal_dart:
    path: ..
  web3dart: ^2.3.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
