name: qrcode_modal_example
description: An example app for QRCode modal

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algorand_dart: ^1.0.1
  walletconnect_dart: ^0.0.6

  # WalletConnect QR code modal
  walletconnect_qrcode_modal_dart:
    path: ..

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
